const BEH_CATALOG = (() => {
  const sections = {
    produce: [
      ["Roma Tomatoes", "14 oz pack", 2.19, ["tomatoes", "roma", "produce"]],
      ["Cherry Tomatoes", "1 pint", 3.49, ["tomatoes", "salad", "produce"]],
      ["Yellow Onions", "2 lb bag", 2.29, ["onions", "produce"]],
      ["Sweet Onions", "2 lb bag", 2.69, ["onions", "produce"]],
      ["Garlic Bulb", "each", 0.79, ["garlic", "produce"]],
      ["Fresh Basil", "0.75 oz", 2.79, ["basil", "herbs", "produce"]],
      ["Fresh Cilantro", "1 bunch", 0.98, ["cilantro", "herbs", "produce"]],
      ["Italian Parsley", "1 bunch", 1.18, ["parsley", "herbs", "produce"]],
      ["Green Bell Pepper", "each", 1.09, ["pepper", "produce"]],
      ["Red Bell Pepper", "each", 1.59, ["pepper", "produce"]],
      ["Jalapeno Peppers", "8 oz", 1.29, ["jalapeno", "produce"]],
      ["Limes", "1 lb bag", 2.48, ["limes", "produce"]],
      ["Lemons", "2 lb bag", 4.98, ["lemons", "produce"]],
      ["Russet Potatoes", "5 lb bag", 4.49, ["potatoes", "produce"]],
      ["Yukon Gold Potatoes", "3 lb bag", 4.98, ["potatoes", "produce"]],
      ["Sweet Potatoes", "2 lb bag", 3.19, ["sweet potatoes", "produce"]],
      ["Broccoli Crowns", "each", 2.09, ["broccoli", "produce"]],
      ["Cauliflower", "each", 3.79, ["cauliflower", "produce"]],
      ["Baby Spinach", "5 oz", 2.98, ["spinach", "greens", "produce"]],
      ["Romaine Hearts", "3 ct", 3.48, ["romaine", "lettuce", "produce"]],
      ["Iceberg Lettuce", "each", 1.98, ["lettuce", "produce"]],
      ["Avocados", "4 ct bag", 4.99, ["avocados", "produce"]],
      ["Cucumbers", "3 ct", 2.68, ["cucumbers", "produce"]],
      ["Carrots", "2 lb bag", 1.98, ["carrots", "produce"]],
      ["Celery", "each", 1.79, ["celery", "produce"]],
      ["Zucchini", "1 lb", 1.99, ["zucchini", "produce"]],
      ["Yellow Squash", "1 lb", 1.99, ["squash", "produce"]],
      ["White Mushrooms", "8 oz", 2.48, ["mushrooms", "produce"]],
      ["Portobello Caps", "2 ct", 3.99, ["mushrooms", "produce"]],
      ["Gala Apples", "3 lb bag", 4.29, ["apples", "fruit", "produce"]],
      ["Bananas", "2 lb bunch", 1.44, ["bananas", "fruit", "produce"]],
      ["Strawberries", "1 lb", 3.98, ["strawberries", "fruit", "produce"]],
      ["Blueberries", "1 pint", 4.48, ["blueberries", "fruit", "produce"]],
      ["Seedless Grapes", "2 lb", 5.49, ["grapes", "fruit", "produce"]],
      ["Fresh Ginger Root", "4 oz", 1.12, ["ginger", "produce"]],
      ["Green Cabbage", "each", 2.08, ["cabbage", "produce"]],
      ["Green Beans", "12 oz", 2.49, ["green beans", "produce"]],
      ["Asparagus", "1 lb", 3.98, ["asparagus", "produce"]],
      ["Raspberries", "6 oz", 4.48, ["raspberries", "fruit", "produce"]],
      ["Blackberries", "6 oz", 4.48, ["blackberries", "fruit", "produce"]],
      ["Pineapple Chunks", "20 oz", 3.98, ["pineapple", "fruit", "produce"]],
      ["Mangoes", "2 ct", 2.98, ["mango", "fruit", "produce"]],
      ["Green Onions", "1 bunch", 1.08, ["green onions", "scallions", "produce"]],
      ["Fresh Dill", "0.5 oz", 2.48, ["dill", "herbs", "produce"]],
      ["Mint Leaves", "0.75 oz", 2.48, ["mint", "herbs", "produce"]],
      ["Baby Bella Mushrooms", "8 oz", 2.78, ["mushrooms", "produce"]],
    ],
    meat: [
      ["Boneless Skinless Chicken Breasts", "1.8 lb avg", 8.94, ["chicken breasts", "meat"]],
      ["Chicken Thighs", "2 lb tray", 6.98, ["chicken thighs", "meat"]],
      ["Ground Beef 90/10", "1 lb", 6.49, ["ground beef", "meat"]],
      ["Ground Turkey", "1 lb", 4.98, ["ground turkey", "meat"]],
      ["Pork Chops", "1.5 lb avg", 9.27, ["pork chops", "meat"]],
      ["Bacon", "12 oz", 5.48, ["bacon", "meat"]],
      ["Italian Sausage", "19 oz", 6.29, ["sausage", "meat"]],
      ["Beef Stew Meat", "1.5 lb avg", 11.48, ["stew meat", "beef", "meat"]],
      ["Salmon Fillets", "1 lb", 12.99, ["salmon", "seafood"]],
      ["Raw Shrimp 31-40 ct", "1 lb", 8.99, ["shrimp", "seafood"]],
      ["Tilapia Fillets", "1 lb", 7.49, ["tilapia", "seafood"]],
      ["Rotisserie Chicken", "each", 7.98, ["rotisserie chicken", "prepared"]],
      ["Deli Oven Roasted Turkey", "9 oz", 5.99, ["deli turkey", "deli"]],
      ["Sliced Honey Ham", "9 oz", 5.99, ["ham", "deli"]],
    ],
    dairy: [
      ["Whole Milk", "1 gallon", 3.98, ["milk", "dairy"]],
      ["2% Milk", "1 gallon", 3.98, ["milk", "dairy"]],
      ["Heavy Whipping Cream", "1 pint", 4.39, ["cream", "dairy"]],
      ["Half and Half", "1 quart", 2.68, ["half and half", "dairy"]],
      ["Salted Butter", "16 oz", 4.48, ["butter", "dairy"]],
      ["Unsalted Butter", "16 oz", 4.48, ["butter", "dairy"]],
      ["Large Eggs", "12 ct", 3.64, ["eggs", "dairy"]],
      ["Greek Yogurt Vanilla", "32 oz", 5.29, ["yogurt", "dairy"]],
      ["Sharp Cheddar Cheese", "8 oz", 3.79, ["cheddar", "cheese", "dairy"]],
      ["Mozzarella Cheese", "8 oz", 3.69, ["mozzarella", "cheese", "dairy"]],
      ["Parmesan Shredded Cheese", "6 oz", 4.48, ["parmesan", "cheese", "dairy"]],
      ["Parmesan Wedge", "5 oz", 5.18, ["parmesan", "cheese", "dairy"]],
      ["Cream Cheese", "8 oz", 2.68, ["cream cheese", "dairy"]],
      ["Sour Cream", "16 oz", 2.49, ["sour cream", "dairy"]],
      ["Cottage Cheese", "24 oz", 3.29, ["cottage cheese", "dairy"]],
      ["Buttermilk", "1 quart", 2.89, ["buttermilk", "dairy"]],
      ["Monterey Jack Cheese", "8 oz", 3.69, ["monterey jack", "cheese", "dairy"]],
      ["Pepper Jack Cheese", "8 oz", 3.79, ["pepper jack", "cheese", "dairy"]],
      ["String Cheese", "12 ct", 4.98, ["string cheese", "dairy"]],
      ["Plain Yogurt", "32 oz", 4.98, ["yogurt", "dairy"]],
    ],
    pantry: [
      ["Spaghetti", "16 oz", 1.88, ["spaghetti", "pasta", "pantry"]],
      ["Penne Pasta", "16 oz", 1.88, ["penne", "pasta", "pantry"]],
      ["Fettuccine", "16 oz", 1.98, ["fettuccine", "pasta", "pantry"]],
      ["Olive Oil", "17 oz", 8.98, ["olive oil", "pantry"]],
      ["Vegetable Oil", "48 oz", 4.98, ["oil", "pantry"]],
      ["Balsamic Vinegar", "16.9 oz", 4.99, ["vinegar", "pantry"]],
      ["Chicken Broth", "32 oz", 2.18, ["broth", "pantry"]],
      ["Beef Broth", "32 oz", 2.18, ["broth", "pantry"]],
      ["Crushed Tomatoes", "28 oz", 2.29, ["tomatoes", "canned", "pantry"]],
      ["Tomato Paste", "6 oz", 1.12, ["tomato paste", "pantry"]],
      ["Black Beans", "15 oz", 1.18, ["beans", "pantry"]],
      ["Pinto Beans", "15 oz", 1.18, ["beans", "pantry"]],
      ["Chickpeas", "15 oz", 1.18, ["chickpeas", "garbanzo", "pantry"]],
      ["Long Grain Rice", "2 lb", 3.98, ["rice", "pantry"]],
      ["Jasmine Rice", "2 lb", 4.88, ["rice", "pantry"]],
      ["Flour Tortillas", "20 ct", 3.68, ["tortillas", "pantry"]],
      ["Corn Tortillas", "30 ct", 2.98, ["tortillas", "pantry"]],
      ["Panko Breadcrumbs", "8 oz", 2.99, ["breadcrumbs", "pantry"]],
      ["Kosher Salt", "48 oz", 2.68, ["salt", "pantry"]],
      ["Black Pepper", "4 oz", 4.48, ["pepper", "pantry"]],
      ["Smoked Paprika", "2.5 oz", 4.98, ["paprika", "spice", "pantry"]],
      ["Ground Cumin", "2.3 oz", 3.98, ["cumin", "spice", "pantry"]],
      ["Italian Seasoning", "0.75 oz", 2.49, ["italian seasoning", "spice", "pantry"]],
      ["Garlic Powder", "3.1 oz", 2.98, ["garlic powder", "spice", "pantry"]],
      ["Brown Sugar", "2 lb", 2.78, ["sugar", "pantry"]],
      ["Granulated Sugar", "4 lb", 3.98, ["sugar", "pantry"]],
      ["All Purpose Flour", "5 lb", 3.79, ["flour", "pantry"]],
      ["Baking Soda", "16 oz", 1.29, ["baking soda", "pantry"]],
      ["Baking Powder", "8.1 oz", 2.29, ["baking powder", "pantry"]],
      ["Vanilla Extract", "2 oz", 5.98, ["vanilla", "baking", "pantry"]],
      ["Peanut Butter", "16 oz", 3.29, ["peanut butter", "pantry"]],
      ["Strawberry Jam", "18 oz", 3.68, ["jam", "pantry"]],
      ["Honey", "12 oz", 4.98, ["honey", "pantry"]],
      ["Soy Sauce", "15 oz", 2.68, ["soy sauce", "pantry"]],
      ["Salsa Roja", "16 oz", 2.98, ["salsa", "pantry"]],
      ["Coconut Milk", "13.5 oz", 2.38, ["coconut milk", "pantry"]],
      ["Red Curry Paste", "4 oz", 3.98, ["curry paste", "pantry"]],
      ["Chicken Gravy Mix", "0.87 oz", 0.88, ["gravy", "pantry"]],
      ["Marinara Sauce", "24 oz", 2.98, ["marinara", "pasta sauce", "pantry"]],
      ["Alfredo Sauce", "15 oz", 3.48, ["alfredo", "pasta sauce", "pantry"]],
      ["Macaroni", "16 oz", 1.68, ["macaroni", "pasta", "pantry"]],
      ["Lasagna Noodles", "16 oz", 2.48, ["lasagna noodles", "pasta", "pantry"]],
      ["Rigatoni", "16 oz", 1.88, ["rigatoni", "pasta", "pantry"]],
      ["Quinoa", "12 oz", 4.98, ["quinoa", "pantry"]],
      ["Rolled Oats", "18 oz", 3.29, ["oats", "breakfast", "pantry"]],
      ["Pancake Mix", "32 oz", 3.68, ["pancake mix", "breakfast", "pantry"]],
      ["Maple Syrup", "12 oz", 6.48, ["syrup", "breakfast", "pantry"]],
      ["Chicken Noodle Soup", "10.5 oz", 1.69, ["soup", "pantry"]],
      ["Tomato Soup", "10.75 oz", 1.69, ["soup", "pantry"]],
      ["Tuna in Water", "5 oz", 1.19, ["tuna", "pantry"]],
      ["Mac and Cheese", "7.25 oz", 1.48, ["mac and cheese", "pantry"]],
      ["Mayonnaise", "30 oz", 4.98, ["mayonnaise", "condiments", "pantry"]],
      ["Yellow Mustard", "14 oz", 1.98, ["mustard", "condiments", "pantry"]],
      ["Ketchup", "20 oz", 2.98, ["ketchup", "condiments", "pantry"]],
      ["Ranch Dressing", "16 oz", 3.48, ["ranch", "condiments", "pantry"]],
      ["Caesar Dressing", "16 oz", 3.48, ["caesar dressing", "condiments", "pantry"]],
    ],
    bakery: [
      ["Sourdough Bread", "24 oz", 4.68, ["bread", "bakery"]],
      ["Sandwich Bread", "20 oz", 2.98, ["bread", "bakery"]],
      ["French Bread", "14 oz", 1.88, ["bread", "bakery"]],
      ["Ciabatta Rolls", "4 ct", 4.48, ["rolls", "bakery"]],
      ["Everything Bagels", "6 ct", 3.78, ["bagels", "bakery"]],
      ["Hamburger Buns", "8 ct", 2.98, ["buns", "bakery"]],
      ["Hot Dog Buns", "8 ct", 2.98, ["buns", "bakery"]],
      ["Flour Tortilla Bakery Pack", "10 ct", 2.68, ["tortillas", "bakery"]],
      ["Blueberry Muffins", "4 ct", 4.98, ["muffins", "bakery"]],
      ["Croissants", "4 ct", 5.49, ["croissants", "bakery"]],
      ["Dinner Rolls", "12 ct", 3.98, ["rolls", "bakery"]],
      ["Cinnamon Raisin Bread", "16 oz", 3.98, ["bread", "bakery"]],
    ],
    frozen: [
      ["Frozen Mixed Vegetables", "12 oz", 1.79, ["frozen vegetables", "frozen"]],
      ["Frozen Broccoli Florets", "12 oz", 1.98, ["broccoli", "frozen"]],
      ["Frozen Pizza Margherita", "18 oz", 6.98, ["pizza", "frozen"]],
      ["Frozen Chicken Nuggets", "22 oz", 5.98, ["nuggets", "frozen"]],
      ["Vanilla Ice Cream", "48 oz", 4.98, ["ice cream", "frozen"]],
      ["Chocolate Ice Cream", "48 oz", 4.98, ["ice cream", "frozen"]],
      ["Frozen Berries", "16 oz", 5.48, ["berries", "frozen"]],
      ["Garlic Bread", "10 oz", 3.48, ["garlic bread", "frozen"]],
      ["Hash Browns", "26 oz", 3.98, ["hash browns", "frozen"]],
      ["Frozen Waffles", "10 ct", 3.48, ["waffles", "frozen"]],
      ["Frozen Mango Chunks", "16 oz", 4.98, ["mango", "frozen"]],
      ["Frozen Peas", "12 oz", 1.79, ["peas", "frozen"]],
      ["Frozen Corn", "12 oz", 1.79, ["corn", "frozen"]],
    ],
    beverages: [
      ["Orange Juice", "52 oz", 4.28, ["juice", "beverages"]],
      ["Apple Juice", "64 oz", 3.48, ["juice", "beverages"]],
      ["Sparkling Water Lime", "8 ct", 4.98, ["sparkling water", "beverages"]],
      ["Cola", "12 ct", 8.48, ["soda", "beverages"]],
      ["Diet Cola", "12 ct", 8.48, ["soda", "beverages"]],
      ["Cold Brew Coffee", "48 oz", 5.98, ["coffee", "beverages"]],
      ["Medium Roast Coffee", "12 oz", 7.98, ["coffee", "beverages"]],
      ["Green Tea Bags", "40 ct", 3.98, ["tea", "beverages"]],
      ["Lemonade", "52 oz", 3.98, ["lemonade", "beverages"]],
      ["Sports Drink Variety", "8 ct", 6.49, ["sports drink", "beverages"]],
      ["Bottled Water", "24 ct", 4.98, ["water", "beverages"]],
      ["Sweet Tea", "1 gallon", 3.28, ["tea", "beverages"]],
      ["Unsweet Tea", "1 gallon", 3.28, ["tea", "beverages"]],
      ["Chocolate Milk", "half gallon", 3.98, ["milk", "beverages"]],
    ],
    snacks: [
      ["Sea Salt Potato Chips", "8 oz", 3.98, ["chips", "snacks"]],
      ["Tortilla Chips", "13 oz", 3.48, ["chips", "snacks"]],
      ["Butter Crackers", "13.7 oz", 3.78, ["crackers", "snacks"]],
      ["Trail Mix", "14 oz", 5.48, ["trail mix", "snacks"]],
      ["Roasted Almonds", "10 oz", 5.98, ["almonds", "snacks"]],
      ["Granola Bars", "12 ct", 4.48, ["granola bars", "snacks"]],
      ["Popcorn", "3 ct", 2.98, ["popcorn", "snacks"]],
      ["Chocolate Sandwich Cookies", "14.3 oz", 4.29, ["cookies", "snacks"]],
      ["Pretzel Twists", "16 oz", 2.98, ["pretzels", "snacks"]],
      ["Dark Chocolate", "3.5 oz", 2.79, ["chocolate", "snacks"]],
      ["Cheddar Popcorn", "6 oz", 3.48, ["popcorn", "snacks"]],
      ["Fruit Snacks", "22 ct", 6.48, ["fruit snacks", "snacks"]],
      ["Peanut Butter Crackers", "8 ct", 3.68, ["crackers", "snacks"]],
    ],
    deli: [
      ["Classic Chicken Salad", "12 oz", 5.98, ["chicken salad", "deli"]],
      ["Potato Salad", "16 oz", 4.29, ["potato salad", "deli"]],
      ["Pimento Cheese Spread", "12 oz", 4.98, ["pimento cheese", "deli"]],
      ["Prepared Guacamole", "8 oz", 4.68, ["guacamole", "deli"]],
      ["Fresh Pico de Gallo", "12 oz", 3.98, ["pico de gallo", "deli"]],
      ["Hummus", "10 oz", 3.48, ["hummus", "deli"]],
      ["Spinach Artichoke Dip", "10 oz", 4.98, ["dip", "deli"]],
      ["Macaroni Salad", "16 oz", 4.29, ["macaroni salad", "deli"]],
    ],
    breakfast: [
      ["Honey Oat Cereal", "12 oz", 4.68, ["cereal", "breakfast"]],
      ["Corn Flakes", "18 oz", 4.29, ["cereal", "breakfast"]],
      ["Granola", "12 oz", 4.98, ["granola", "breakfast"]],
      ["Blueberry Toaster Pastries", "8 ct", 3.29, ["pastries", "breakfast"]],
      ["Breakfast Sausage Links", "12 oz", 4.98, ["sausage", "breakfast"]],
      ["Turkey Bacon", "12 oz", 4.98, ["bacon", "breakfast"]],
      ["Frozen Breakfast Burritos", "8 ct", 8.98, ["burritos", "breakfast"]],
      ["Orange Marmalade", "18 oz", 3.98, ["jam", "breakfast"]],
    ],
    household: [
      ["Paper Towels", "6 rolls", 9.98, ["paper towels", "household"]],
      ["Toilet Paper", "12 rolls", 13.48, ["toilet paper", "household"]],
      ["Dish Soap", "19.4 oz", 3.98, ["dish soap", "household"]],
      ["Laundry Detergent", "92 oz", 12.98, ["detergent", "household"]],
      ["Trash Bags", "40 ct", 7.98, ["trash bags", "household"]],
      ["Aluminum Foil", "75 sq ft", 4.98, ["foil", "household"]],
      ["Plastic Wrap", "200 sq ft", 3.98, ["wrap", "household"]],
      ["Sponges", "6 ct", 4.49, ["sponges", "household"]],
    ],
  };

  const labels = {
    produce: "Produce",
    meat: "Meat & Seafood",
    dairy: "Dairy & Eggs",
    pantry: "Pantry",
    bakery: "Bakery",
    frozen: "Frozen",
    beverages: "Drinks",
    snacks: "Snacks",
    deli: "Prepared Foods",
    breakfast: "Breakfast",
    household: "Home",
  };

  const catalog = [];
  let index = 1;

  Object.entries(sections).forEach(([category, items]) => {
    items.forEach(([name, size, price, keywords]) => {
      const slug = `${name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}-${index}`;
      catalog.push({
        id: slug,
        sku: `BEH-${String(index).padStart(4, "0")}`,
        name,
        size,
        price,
        category,
        categoryLabel: labels[category],
        keywords,
      });
      index += 1;
    });
  });

  return catalog;
})();
